package commander;

public enum CommandEnum {
    HELP,
    INFO,
    SHOW,
    ADD,
    UPDATE,
    REMOVE_BY_ID,
    CLEAR,
    SAVE,
    EXECUTE_SCRIPT,
    EXIT,
    REMOVE_GREATER,
    REMOVE_LOWER,
    HISTORY,
    MAX_BY_GROUP_ADMIN,
    FILTER_LESS_THAN_SEMESTER_ENUM,
    PRINT_FIELD_DESCENDING_GROUP_ADMIN
}
